[package]
name = "polars-vstack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
divan = "0.1.11"
polars-core = "0.37.0"


[[bench]]
name = "vstack"
harness = false